In [4]:
d = date()
cat("Today's date is:", d, "\n")

x = 1:10
cat(x, sep = " ++ ")
cat("\n")
cat(x, sep = " / ")

x = 7
cat("The square of", x, "is", x^2, "!\n")

cat("The square root of", x, "is approximately", format(sqrt(x), digits=3), "\n")

evenno = c(2,4,6,8,10)
cat("The first few even numbers are:", evenno, "...\n")

x = 1:10
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

Today's date is: Wed Sep 23 04:00:54 2026
1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10The square of 7 is 49 !
The square root of 7 is approximately 2.65
The first few even numbers are: 2 4 6 8 10 ...
( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [5]:
paste(1:12)
as.character(1:12)

paste("Everybody", "loves", "R Programming.")
paste("Everybody", "loves", "R Programming.", sep="*")
paste("Everybody", "loves", "R Programming.", sep="===")

names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
paste(names, "is", "a good", "person.")

paste(names, "is", "a good", "person.", collapse=", and ")

paste0("Everybody", "loves", "R Programming.")

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

[1] "Everybody loves R Programming."

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

[1] "EverybodylovesR Programming."

In [6]:
x= paste("Ex",1:5,sep="_")
x
x[1]
x[2]
x[3]
x[5]

x=paste("Ex",1:5,sep="_",collapse="")
x[1]

paste0(1:10)
paste(1:10)

paste0(1:10,c("st","nd","rd",rep("th",7)))
paste(1:10,c("st","nd","rd",rep("th",7)))

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [8]:
x = "The&!syntax&!of&!paste&!is!&available!&inthe online-help"
x
strsplit(x, split="!")
strsplit(x, split="&!")
y = strsplit(x, split="!&")
y
y[[1]][1]
y[[1]][2]
y[[1]][3]

[1] "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

[[1]]
[1] "The&"               "syntax&"            "of&"
[4] "paste&"             "is"                 "&available"
[7] "&inthe online-help"

[[1]]
[1] "The"                              "syntax"
[3] "of"                               "paste"
[5] "is!&available!&inthe online-help"

[[1]]
[1] "The&!syntax&!of&!paste&!is" "available"
[3] "inthe online-help"

[1] "The&!syntax&!of&!paste&!is"

[1] "available"

[1] "inthe online-help"

In [9]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")

datesplt = strsplit(dates, "-")
datesplt

datemat = matrix(unlist(datesplt), nrow=4, ncol=3, byrow=TRUE)
datemat

datematrix = matrix(as.numeric(unlist(datesplt)), nrow=4, ncol=3, byrow=TRUE)
datematrix

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [10]:
strsplit("Shalabh", split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

In [11]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

nchar(x)
nchar(y)

x = c("Apple", "Banana", "Cake")
nchar(x)

y = c(2, 4, 6)
nchar(y)

z = c(11, 222, 3333)
nchar(z)

z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 19

[1] 26

[1] 5 6 4

[1] 1 1 1

[1] 2 3 4

[1] 3 4 5

In [12]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

nzchar(x)
nzchar(y)

x = c("Apple", "Banana", "Cake")
nzchar(x)

y = c("Apple", "", "Cake")
nzchar(y)

[1] TRUE

[1] TRUE

[1] TRUE TRUE TRUE

[1]  TRUE FALSE  TRUE

In [13]:
x="R course will start from 24.07.2022"
toupper(x)

z="INDIAN INSTITUTE OF TECHNOLOGY"
tolower(z)

[1] "R COURSE WILL START FROM 24.07.2022"

[1] "indian institute of technology"