NAME :- ASHA BHOKARE

ROLL NO.:- 23102A0032

R PROGRAMMING TASK 2

In [ ]:
c(2,3,5,7)+c(-2,-3,-5,8)

[1]  0  0  0 15

In [ ]:
2^3
2**3
2^0.5
2**0.5
2^-0.5

[1] 8

[1] 8

[1] 1.414214

[1] 1.414214

[1] 0.7071068

In [ ]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [ ]:
c(2,3,5,7)^c(2,3)
c(1,2,3,4,5,6)^c(2,3,4)
c(2,3,5,7)^c(2,3,4)

[1]   4  27  25 343

[1]    1    8   81   16  125 1296

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [ ]:
2 %/% 2
5 %/% 2
7 %/% 3
c(2,3,5,7) %/% 2

[1] 1

[1] 2

[1] 2

[1] 1 1 2 3

In [ ]:
c(2,3,5,7) %/% c(2,3)
c(2,3,5) %/% c(2,3)

[1] 1 1 2 2

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [ ]:
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

[1] 3.4

[1] 3.4

[1] -7.8

[1] -7.8

In [ ]:
mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 2

[1] 3

In [ ]:
abs(-4)
abs(c(-1,-2,-3,4,5))

[1] 4

[1] 1 2 3 4 5

In [ ]:
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2

[1] 2 3 4 5

In [ ]:
sum(c(2,3,5,7))
prod(c(2,3,5,7))

[1] 17

[1] 210

In [ ]:
round(1.23)
round(1.83)

[1] 1

[1] 2

In [ ]:
log(20)
log(exp(1))
log(c(10,100,1000))

[1] 2.995732

[1] 1

[1] 2.302585 4.605170 6.907755

In [ ]:
log10(10)
log10(100)
log10(c(10, 100, 1000))

[1] 1

[1] 2

[1] 1 2 3

In [ ]:
x1=c(1,2,3,4)
x1
x2 = x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

In [ ]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))
abs(c(1,2,3,4) - sum(c(1,2,3,4)) * prod(c(1,2)))

[1] 21 22 23 24

[1] 19 18 17 16

In [ ]:
x= matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
x[3,2]

[1] 7

In [ ]:
y = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=TRUE)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
dim(x)
nrow(x)
ncol(x)

[1] 4 2

[1] 4

[1] 2

In [ ]:
mode(x)
attributes(x)

[1] "numeric"

$dim
[1] 4 2

In [ ]:
x=matrix(nrow=4, ncol=2, data=c(1:12))
x

Warning message in matrix(nrow = 4, ncol = 2, data = c(1:12)):
“data length differs from size of matrix: [12 != 4 x 2]”

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
x=matrix(nrow=4, ncol=2, data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [ ]:
d= diag(1, nrow=3, ncol=3)
d
d= diag(5, nrow=3,ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
xt = t(x)
xt

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [ ]:
x= matrix(nrow=4, ncol=2 , data=c(1,2,3,4,5,6,7,8))
x
rowSums(x)
colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

In [ ]:
rowMeans(x)
colMeans(x)

[1] 3 4 5 6

[1] 2.5 6.5

In [ ]:
x = matrix(nrow=5, ncol=3, byrow=T, data=1:15)
x
x[3,]
x[,2]
x[4:5, 2:3]
x[c(1,4), c(1,3)]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

[1] 7 8 9

[1]  2  5  8 11 14

     [,1] [,2]
[1,] 11   12
[2,] 14   15

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [ ]:
x= matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
x+5
x-5
5*x
x/2

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
x
y
x+y
x-y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [ ]:
4*x
x + 4*x
4*x - x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
x%*%y
y%*%x
t(x) %*% x
x %*% t(x)
crossprod(x)

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
rbind(x, y)
cbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [ ]:
y = matrix(nrow=2, ncol=2, byrow=T, data=c(84,100,100,120))
y
solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [ ]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [ ]:
x=8
(x < 10) || (x < 2)
x=18
(x < 10) || (x < 2)

[1] TRUE

[1] FALSE

In [ ]:
x=c(8,18)
(x< 10) | (x< 2)

[1]  TRUE FALSE

In [ ]:
x = 5
(x < 10) && (x > 2)
x = 15
(x < 10) && (x > 2)
x = c(8,18)
(x < 10) & (x > 2)

[1] TRUE

[1] FALSE

[1]  TRUE FALSE

In [ ]:
x = 1:6
(x > 2) & (x < 5)
x[(x > 2) & (x < 5)]
(x > 2) | (x < 5)
x[(x > 2) | (x < 5)]
(x[1] > 2) & (x[1] < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

[1] FALSE

In [ ]:
x= TRUE
y = FALSE
x & y
x | y
!x

[1] FALSE

[1] TRUE

[1] FALSE

In [ ]:
x = 5
Logical1 = (x > 2)
Logical1
is.logical(Logical1)
Logical2 = (x < 10)
Logical2
is.logical(Logical2)
Logical3 = (x != 5)
Logical3
is.logical(Logical3)
Logical4 = (2*x > 11)
Logical4
is.logical(Logical4)
Logical5 = (3*x <20)
Logical5
is.logical(Logical5)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

In [ ]:
8>7
7<5
7>7
7>=7
8<8
8<=8
8!=9
9 != 9
7 == 7
7 == 8
x = TRUE
!x

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

In [ ]:
x = c(1, 2, 3)
y = c(4, 5, 6)
x > y
x < y
x != y
x == y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

In [ ]:
isTRUE(8 < 6)
isTRUE(8 > 6)
isFALSE(5 < 8)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE